[package]
name = "wish"
version = "0.2.0"
authors = ["Mario Geiger <geiger.mario@gmail.com>"]

[dependencies]
iron = "*"
router = "*"

bson = "0.3.2"
mongodb = "0.2.0"

rustc-serialize = "*"
rand = "*"
time = "*"
lettre = "*"
