[package]
name = "wish"
version = "0.1.0"
authors = ["Mario Geiger <geiger.mario@gmail.com>"]

[dependencies]
iron = "*"
router = "*"

bson = "*"
mongodb = "*"

rustc-serialize = "*"

rust-crypto = "*"
rand = "*"
time = "*"
num_cpus = "*"
